### ISSUE TITLE
extract_merge_request_id_from_commit only extracts first digit of merge request

### ISSUE THREAD

**Issue by chrisowensKEB** [mrooding/gitlab-semantic-versioning#1]
The regex in extract_merge_request_id_from_commit() function only captures the first digit of a merge request.

```python
matches = re.search(r'(\S*\/\S*!)(\d)', message.decode("utf-8"), re.M|re.I)
```

Simply adding + to the `(\d)` should do the trick as shown below:

```python
matches = re.search(r'(\S*\/\S*!)(\d+)', message.decode("utf-8"), re.M|re.I)
```

**Comment by mrooding** [comment]
Hi @chrisowensKEB 

Thanks for bringing my attention to this. I already updated the snippet used in the blog post but completely forgot about the sample project.
