### ISSUE TITLE
Gitlab login token

### ISSUE THREAD

**Issue by Mertonidas** [mrooding/gitlab-semantic-versioning#4]
Hi Marc,

Firts at all, thank you for this project.

Maybe will be better use a gitlab access token instead of user/password for security resasons.

Thank you

Best regards

**Comment by kayman-mk** [comment]
Use the token as NPA_PASSWORD. That's the way it is woking in my CI system.

**Comment by mrooding** [comment]
@Mertonidas The name `NPA_PASSWORD` may be a bit misleading. If you take a look at the `README.md` you can see that I actually instruct you to generate a personal access token for the NPA user and set this to `NPA_PASSWORD`. I'll mark this as closed for now. Please re-open if you feel that there's more to go in to.
