### ISSUE TITLE
Make labels configurable through env vars

### ISSUE THREAD

**Issue by janjagusch** [mrooding/gitlab-semantic-versioning#5]
**Hi, thanks for starting this project!**

I would like to specify custom label names, e.g. "Removal" and "Feature" instead of "bump-major" and "bump-minor". I believe making this configurable through environment variables (with "bump-major" and "bump-minor" as defaults)  would really help many people out.

I'd be glad to do a PR on this one. :)

**Comment by janjagusch** [comment]
thanks for merging @mrooding!

are you planning on making this a release (e.g. v1.1.0)? would be super useful to get this feature straight from dockerhub.

**Comment by mrooding** [comment]
Docker hub just built a new version and tagged it as `latest`. If you prefer, I can create a release for 1.1.0 so that you can use a semver tag for the image itself.

**Comment by janjagusch** [comment]
> Docker hub just built a new version and tagged it as `latest`. If you prefer, I can create a release for 1.1.0 so that you can use a semver tag for the image itself.

yeah that would be awesome! thank you!

**Comment by mrooding** [comment]
the 1.1.0 tag has been released. Thanks again for the contribution @janjagusch !
