### ISSUE TITLE
Extract merge request labels directly from commit

### ISSUE THREAD

**Issue by janjagusch** [mrooding/gitlab-semantic-versioning#7]
Hi!

I believe I found a way to extract the merge request labels directly from the merge commit.

The idea is that a merge commit always has two parent commits. The first one is the previous commit in the master branch, the second one the the previous commit in the feature branch

Using the [python gitlab sdk](https://pypi.org/project/python-gitlab/):

```python
def get_feature_merge_request(project, commit):
    mr_iid = project.commits.get(commit.parent_ids[-1]).merge_requests()[0]["iid"]
    return project.mergerequests.get(mr_iid)
```

Getting the `project` and `commit` object should be straightforward with the environment variables provided by the Gitlab CI.

```python
import os

gl = gitlab.Gitlab('http://10.0.0.1', job_token=os.environ['CI_JOB_TOKEN'])
gl.auth()

project = gl.project.get(os.environ["CI_PROJECT_ID"])
commit = project.commits.get(os.environ["CI_COMMIT_SHA"])
```

Putting it all together:

```python
>>> get_feature_merge_request(project, commit).labels
["bump-minor"]
```

I believe this has two advantages:

* It removes the regex parsing logic from your codebase (critical if they ever change the structure of the squashed commit message)
* It should also work **without squashing the commits**

---

I think this look pretty promising - but maybe I'm missing something? :thinking: 
What do you think? Does anything speak against this approach?

**Comment by NikolaiGulatz** [comment]
@janjagusch Nice idea. Does this work with *all* available merge methods which you can select in the project settings in GitLab?

![Screen Capture_select-area_20200624101838](https://user-images.githubusercontent.com/11081876/85521203-31cf1200-b604-11ea-9afb-77661f816964.png)

**Comment by janjagusch** [comment]
> @janjagusch Nice idea. Does this work with _all_ available merge methods which you can select in the project settings in GitLab?
> 
> ![Screen Capture_select-area_20200624101838](https://user-images.githubusercontent.com/11081876/85521203-31cf1200-b604-11ea-9afb-77661f816964.png)

Good point, will check later.

**Comment by kayman-mk** [comment]
@janjagusch  Guess it will not work for the "fast-forward merge". I did some experiments but nothing worked.
